import { StandardMerkleTree } from "@openzeppelin/merkle-tree";
import fs from "fs";

// Read the CSV generated by generate_sample_massive_spline.py
var values = fs.readFileSync('massive_spline.csv')
    .toString() // convert Buffer to string
    .trim() // remove white spaces
    .split('\n') // split string to lines
    .map(e => e.trim()) // remove white spaces for each line
    .map(e => e.split(',').map(e => e.trim())); // split each line to array

// Generate the tree
const tree = StandardMerkleTree.of(values, ["int256", "int256", "int256", "int256", "int256", "int256"]);

// Print the Merkle Root
console.log('Merkle Root:', tree.root);

// Save the tree
fs.writeFileSync("massive_spline_merkle_tree.json", JSON.stringify(tree.dump()));
